### ISSUE TITLE
\ inside rules is not escaped

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#10] opened 2019-09-03 11:24 UTC
`your name HAS to be \`

## Expected Behavior
code look should look like this
`your name HAS to be \\`

## Current Behavior
instead I the generated code has the plain `\` escaping the final quotation mark
````
"your name HAS to be \",
````

````js
huml.appendRule("",
    ["name"],
    "your name HAS to be \",
    function(model) { 
        return huml.NOT_EQUALS(model.name, "to");
    },
    false
);
````
## Possible Solution
Properly escape `\`

## Your Environment
Playground

**Comment by jages** [comment] 2020-01-31 13:37
Adding this as a duplicate of #29 .

**Closed by jages** 2020-01-31 13:37 UTC
Labels: bug, codegen
