### ISSUE TITLE
playground: error while compile language 

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#13] opened 2019-09-04 09:10 UTC
The following code causes a compile error on the playground
````
foo AS bar

bar AS foo

your name has to be foo

````
"Error while compile language Javascript:"

**Comment by NLueg** [comment] 2019-10-08 06:38
I tried to reproduce this error and maybe got a more useful error message.
I get the error `java.lang.Exception: java.lang.StackOverflowError`.

This is probably because of the recursive usage of both variables.
Should recursive usage be possible @thecodemonkey @jages? 
Maybe we at least should provide a more informative error message in this case.

**Comment by jages** [comment] 2020-01-31 12:56
Currently, this generates a compile error.
There is (somewhat) of a failsave, as in: if one of the variables is also in the model, this throws an error at generation time.
Currently there is no other mechanism in place to search for recursive calls in the generated code, as this might limit our ability to generate code.

I'm closing this issue, but have not made up how to finaly approach this problem without introducing further roadblocks down the pipeline.

**Closed by jages** 2020-01-31 12:56 UTC
Labels: bug
